# Generated by Django 2.2.1 on 2019-05-24 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department_Name', models.CharField(max_length=25)),
                ('Department_Number', models.CharField(max_length=25)),
            ],
        ),
    ]
