# Generated by Django 2.2.1 on 2019-05-22 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profesor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profesor',
            old_name='FirstName',
            new_name='First_Name',
        ),
        migrations.RenameField(
            model_name='profesor',
            old_name='LastName',
            new_name='Last_Name',
        ),
        migrations.AddField(
            model_name='profesor',
            name='Email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
